PORTNAME=	cpdup
PORTVERSION=	1.22
CATEGORIES=	sysutils

MAINTAINER=	gmarco@giovannelli.it
COMMENT=	Comprehensive filesystem mirroring and backup program
WWW=		https://github.com/freebsd/cpdup

LICENSE=	BSD2CLAUSE # clarified by Matthew Dillon himself

USES=		ssl tar:xz
USE_GITHUB=	yes
GH_ACCOUNT=	freebsd
GH_TAGNAME=	main
MAKEFILE=	Makefile.bsd

PLIST_FILES=	bin/cpdup \
		man/man1/cpdup.1.gz

.include <bsd.port.mk>
